### ISSUE TITLE
Enable the functionality of Debates on Decidim-barcelona-organizations instances

### ISSUE THREAD

**Issue by josanFFiG** [AjuntamentdeBarcelona/decidim-barcelona-organizations#10]
# This is a Bug report:

#### :tophat: Description

Debates functionality is missing in the instances on Decidim-barcelona-organizacions instances (decidm 0.8.3).

#### :clipboard: Additional Data

![captura de 2017-12-18 15-58-44](https://user-images.githubusercontent.com/27766903/34112293-6ce80bfc-e40c-11e7-8d2d-6eaf3851a6b4.png)

* ***Decidim deployment where you found the issue***:
* ***Browser & version***:
* ***Screenshot***:
* ***Error messages***:
* ***URL to reproduce the error***:

**Comment by zuzust** [comment]
It is not really a bug though. The thing is that this module is not included in the app Gemfile, and we need it @josepjaume

**Comment by josanFFiG** [comment]
Hi there @zuzust and @josepjaume!
How do we get this topic?
This functionality is important for organizations. They will also need that users can open Debates why themselves whitin an open process.

**Comment by zuzust** [comment]
@josanFFiG Regarding the ability of registered users to open debates themselves, it is being faced right now. Follow up on decidim/decidim#1337. It's planned to be included in 0.9 or 0.10
