### ISSUE TITLE
Admins for Assemblies

### ISSUE THREAD

**Issue by josanFFiG** [AjuntamentdeBarcelona/decidim-barcelona-organizations#7]
# This is a Feature Proposal

#### :tophat: Description

Assemblies need to have specific Admins, just like processes have. The final solution to a fine-grained hierarchy of permissions for admins will take some time (see decidim/decidim#2023). And we need to implement this for Assemblies.

#### :pushpin: Related issues

decidim/decidim#2350

#### :clipboard: Additional Data

* ***Decidim deployment where you found the issue***:
* ***Browser & version***:
* ***Screenshot***:
* ***Error messages***:
* ***URL to reproduce the error***:

**Comment by zuzust** [comment]
@mrcasals It seems that this feature is ready and will be included in 0.9, right?

**Comment by mrcasals** [comment]
@zuzust yes, it is and it will! 😄

**Comment by zuzust** [comment]
@mrcasals oh yeah! When will it be published?

**Comment by mrcasals** [comment]
There's no release date yet, but my guess is before the end of the month for sure!= @zuzust

**Comment by zuzust** [comment]
We'll be looking forward to it ;) Thanks! @mrcasals
