### ISSUE TITLE
Identify users supporting (or not) a proposal

### ISSUE THREAD

**Issue by josanFFiG** [AjuntamentdeBarcelona/decidim-barcelona-organizations#9]
# This is a Feature Proposal

#### :tophat: Description

Organizations need to Identify users support on a proposal in order to work with user/s: for understanding their point of view, to rewrite proposal/s together, etc... 
So user support visibility could be an interesting feature.

#### :pushpin: Related issues

decidim/decidim#2287
decidim/design#156

#### :clipboard: Additional Data

* ***Decidim deployment where you found the issue***:
* ***Browser & version***:
* ***Screenshot***:
* ***Error messages***:
* ***URL to reproduce the error***:

**Comment by zuzust** [comment]
@josanFFiG the actual feature that is being developed makes some assumptions that we need to check out:

- While votes and supports are secret, endorsements might be publicly displayed. Would public **endorsement** fulfill this use case?
- Only **verified** groups and individulas will be able to endorse a proposal. Is this requirement valid in our use case?
- The author of the proposal receive a notification when someone endorses the proposal
- The followers of the proposal don't receive a notification when someone endorses the proposal.
- All followers of the participant X that endorses Y should receive a notification that X has endorsed Y

What do you say?

**Comment by josanFFiG** [comment]
1. Sure: endorsement will fullfill this using case.
2. That's the point.
3. 4. and 5. Totally agree with the flow.
Can't wait for release 0.9! ;P

**Comment by zuzust** [comment]
When 0.9 is released I will update to get that feature and I'll ping you back @josanFFiG . I close the issue.
